config/routes.rb
Rails.application.routes.draw do
  root 'demo#search'
  get 'demo/search'
  get 'demo/show'
  get 'demo/list'
  get 'demo/engage'
  get 'demo/reindex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :answers
  resources :questions
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :theme)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Title
  <%= form.text_field :title %>
  <br>
  Theme
  <%= form.text_field :theme %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.grand_debat_id %></td>
        <td><%= question.theme %></td>
        <td><%= question.answers.size %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>